### ISSUE TITLE
bad argument #1 to 'pkg_load'

### ISSUE THREAD

**Issue by smferris** [Kiwi/clyde#102]
Clyde v0.03.12 - lualpm v0.02

`sudo clyde -S dnssec-root-zone-trust-anchors` fails with:

lua: /usr/share/lua/5.1/clydelib/aur.lua:369: bad argument #1 to 'pkg_load' (string expected, got nil)
stack traceback:
    [C]: in function 'pkg_load'
    /usr/share/lua/5.1/clydelib/aur.lua:369: in function 'pkg_ver'
    /usr/share/lua/5.1/clydelib/aur.lua:378: in function </usr/share/lua/5.1/clydelib/aur.lua:377>
    [C]: in function 'sort'
    /usr/share/lua/5.1/clydelib/aur.lua:381: in function 'installpkg'
    /usr/share/lua/5.1/clydelib/sync.lua:1144: in function </usr/share/lua/5.1/clydelib/sync.lua:1070>
    (tail call): ?
    /usr/share/lua/5.1/clydelib/sync.lua:1571: in function 'clyde_sync'
    /usr/share/lua/5.1/clydelib/sync.lua:1577: in function </usr/share/lua/5.1/clydelib/sync.lua:1576>
    (tail call): ?
    /usr/bin/clyde:1056: in function 'main'
    /usr/bin/clyde:1114: in main chunk
    [C]: ?

**Comment by juster** [comment]
Does this happen with every package you build?

**Comment by smferris** [comment]
I tried 3dchess and 4dtris from AUR, and they both failed the same way, so it seems like anything from AUR is going to die this way.

**Comment by smferris** [comment]
I built clyde from git commit 341bff314c65d6a62981a2c1f1397773767ce289.  Installing binary packages works fine.

**Comment by juster** [comment]
I just pushed a tiny bugfix in that general location: b36add6b474e2d0f7ced857064243402925b7017

The bug might be related to yours but I don't know. That sounds really strange and I am still not sure what is causing it. What package files do you have built after it crashes?

There should be some .pkg.tar.xz files built in the relevant directory. Something like /tmp/clyde-smferris/3dchess/3dchess/3dchess-0.8.1-1-i686.pkg.tar.xz

**Comment by smferris** [comment]
After pulling 2b15fcbb0cd19745ac061d2d52dd3b6879d2134d and updating clyde, it's working fine now.   Thanks.

**Comment by juster** [comment]
Cool! Let me know if it crops up again.

**Comment by smferris** [comment]
It's not crashing like it was, but I've now realized it's not actually installing the AUR packages that get built either.  Rather than install what was built, it seems to want to install another package called pinktrace.

==> Leaving fakeroot environment.
==> Finished making: perl-net-dns-sec 0.160.0-1 (Sun Feb 20 00:02:38 CST 2011)
loading package data...
resolving dependencies...
looking for inter-conflicts...
checking package integrity...
(1/1) upgrading pinktrace                          [##############################################################] 100%

I eventually hit Control-C since it stopped printing anything, though lua was taking 10-20% of the cpu until I killed it.  I'll try to experiment more tomorrow and see if I can figure out what's going wrong.

**Comment by juster** [comment]
So where is the pinktrace package file located? What package file is being created for perl-net-dns-sec and where is it?

**Comment by smferris** [comment]
My /etc/makepkg.conf sets PKGDEST=/home/repo/packages, so all the packages I build end up there.   That dir contains pinktrace and all of the AUR packages clyde has been building.

-rw-r--r-- 1 smferris users    77452 Feb 20 00:16 perl-net-dns-sec-0.160.0-1-x86_64.pkg.tar.xz

-rw-r--r-- 1 smferris users    58668 Dec 29 21:46 pinktrace-20101229-1-x86_64.pkg.tar.xz

The packages would get rebuilt if I re-ran clyde -S.  Clyde doesn't always get stuck after building the package, sometimes it just installs pinktrace and moves on.  I was trying to install dnssec-tools, which would pull in a bunch of perl libraries, and it was installing pinktrace for each of them.  With enough packages eventually clyde would get stuck on one of them.  

I eventually worked around the problem by doing a repo-add of the packages after they got built successfully, running clyde -Sy to resynch my repos, and then installing the binary packages from my private repo.

**Comment by juster** [comment]
ah I know what the problem is now I will try to fix it real quick

**Comment by juster** [comment]
Ok I just pushed a commit that should fix it. (d1efe3363d0c5c27e18961eb3331f08952413c82)
Reinstall clyde-git and see if it works.

(Or however you want to package and install it)

**Comment by smferris** [comment]
Seems to be working now.  Thanks.
