### ISSUE TITLE
AUR upgrade fails, unable to build anything else from AUR afterwards

### ISSUE THREAD

**Issue by vendion** [Kiwi/clyde#109]
I am having a werid issue working with packages out of the AUR with Clyde v0.03.14, when doing a system upgrade including packages out of the AUR if a package fails to build clyde is left in a condidtion where it is unable to parse any other AUR pacakes.

Here is the output of some commands on my system https://gist.github.com/850338

**Comment by juster** [comment]
Have you tried re-installing clyde? There was a bug about a week ago when the AUR website changed the location of PKGBUILD files. Namely clyde's check to see if an AUR package existed always returned true. I have updated the github repo with working code but I did not increment the version number past 0.03.14 to indicate the changes.

**Comment by vendion** [comment]
Yes I grabbed the PKGBUILD file from the master branch two days ago and re-installed using that.

**Comment by juster** [comment]
That is pretty bizarre I am still trying to figure it out.

**Comment by vendion** [comment]
Any kind of useful debugging information I can provide?  Does Clyde log output somewhere?  It seems that the only way around this is to rebuild and install clyde from the AUR.

**Comment by juster** [comment]
Give me a day or two and I will look at this. I have a midterm today but spring break is next week...

There really is no state saved by clyde that should affect you in this way. It either finds the package on the AUR or it doesn't, there is no fancy state saved that would be overwritten or cleared by reinstallation. There is no state saved during an upgrade that is somehow fouled up when a package fails to build...

**Comment by juster** [comment]
This might be fixed by a recent update which changes the default umask used.

**Comment by vendion** [comment]
It works as expected using the version I installed this morning thank you!  Sorry it took so long to confirm I had to file a AUR package that failed during its build.
