### ISSUE TITLE
Pacman 3.5 (from Testing) broke clyde

### ISSUE THREAD

**Issue by nexxx** [Kiwi/clyde#115]
Pacman update to version 3.5+ broke clyde.

lua: error loading module 'lualpm' from file '/usr/lib/lua/5.1/lualpm.so':
        /usr/lib/lua/5.1/lualpm.so: undefined symbol: alpm_sync_dbtarget
stack traceback:
        [C]: ?
        [C]: in function 'require'
        /usr/share/lua/5.1/clydelib/util.lua:2: in main chunk
        [C]: in function 'require'
        /usr/bin/clyde:5: in main chunk
        [C]: ?

**Comment by juster** [comment]
Should be fixed now. Re-build/re-install clyde
