### ISSUE TITLE
Request: Never run as root; call sudo/su only when neccessary

### ISSUE THREAD

**Issue by nogweii** [Kiwi/clyde#12]
This is a lazyman request, but it would be nice if clyde would prevent being ran as root (yay, security) but when the user asks to do something (like -S) then clyde can call sudo/su. Not sure how that would work, but I think it would be nice.

**Comment by Kiwi** [comment]
Probably not happening. See here. http://bbs.archlinux.org/viewtopic.php?pid=721027#p721027
Also read through the thread to find bash functions that make it behave more like what you want.

**Comment by nogweii** [comment]
Brilliant! (I use Zsh, btw, but others have already figured that out)

Perhaps you can include a generalized shell script (in some sort of contrib/ folder or w/e) that is shipped with clyde?

EDIT: This version (just removing the c() {} bits) seems to work very well... http://bbs.archlinux.org/viewtopic.php?pid=723161#p723161
