### ISSUE TITLE
Clyde doesn't build hg packages

### ISSUE THREAD

**Issue by rickeyski** [Kiwi/clyde#124]
Clyde works great for svn or git aur packages; however, it won't  create correct directory permissions to allow hg packages. It will show determining latest hg revision, then abort saying permission is denied for ./src/$pkgname. the error message is then unknown error, aur.lua:414, makepkg returned 256.  The package will build if you clone the hg repository manually and then run clyde -S $pkgname

Let me know if you need any other information or if I'm an idiot.  thanks

**Comment by juster** [comment]
Should be fixed now, thanks for mentioning it. I saw it on the bbs too but didn't have time to look at it until today.

**Comment by rickeyski** [comment]
Awesome, thanks.
