### ISSUE TITLE
yajl 2.0.0-1 breaks clyde

### ISSUE THREAD

**Issue by anish** [Kiwi/clyde#125]
lua: error loading module 'yajl' from file '/usr/lib/lua/5.1/yajl.so':
        libyajl.so.1: cannot open shared object file: No such file or directory
stack traceback:
        [C]: ?
        [C]: in function 'require'
        /usr/share/lua/5.1/clydelib/sync.lua:2: in main chunk
        [C]: in function 'require'
        /usr/bin/clyde:6: in main chunk
        [C]: ?

**Comment by rickeyski** [comment]
This looks like a problem with lua-yajl rather than clyde.  I think I narrowed it down to yajl_gen_alloc2 got removed in yajl-2.

**Comment by anish** [comment]
Yeah, try symlinking libyajl.so.2 as libyajl.so.1 and it complains about yajl_gen_alloc2

**Comment by rickeyski** [comment]
trying to recompile lua-yajl generated about 22 or so different errors, mainly with incompatible pointer types, several functions with too many args, and a few structs that are no more.  yajl_gen_alloc is present in yajl-2, but it looks like the headers have been nearly completely rebased.  I will fork lua-yajl and see what I can hunt down

**Comment by juster** [comment]
Falconindy was kind enough to patch lua-yajl for us: falconindy/lua-yajl . Install the new lua-yajl-git from the AUR.
