### ISSUE TITLE
Please give more space to the package name column...

### ISSUE THREAD

**Issue by lch-xx** [Kiwi/clyde#129]
...when there's enough horizontal space available. (Just like pacman does).

This annotated screen-shot should demonstrate the issue:

http://img845.imageshack.us/img845/9683/clydecolumns.png

**Comment by sebnow** [comment]
sebnow/clyde@445e3ae6e64403ecc5c8eaa8be67ae276219b5f7 fixes this by giving the info part 60% of the screen (replicates pacman). Sent a [pull request](https://github.com/Kiwi/clyde/pull/134).

**Comment by juster** [comment]
Merged sebnow's pull request. Thanks!
