### ISSUE TITLE
crashes when attempting to create new clyde.conf

### ISSUE THREAD

**Issue by ijzer** [Kiwi/clyde#135]
[ijzer@HMSHotspur: inspire]$ sudo clyde -S ttf-freebanglafont
Password: 
You do not yet have a clyde.conf, would you like to create one? [Y/n] y
Please enter your default text editor: emacs
You entered 'emacs' as your default editor, is this correct?  [Y/n] y
lua: /usr/bin/clyde:705: bad argument #3 to 'format' (string expected, got table)
stack traceback:
        [C]: in function 'format'
        /usr/bin/clyde:705: in function 'config_init'
        /usr/bin/clyde:1056: in function 'main'
        /usr/bin/clyde:1181: in main chunk
        [C]: ?

the problem is that the program is attempting to set BuildUser in the config file as aur.get_builduser(), which returns a table, not a string. i am fairly sure that the BuildUser option should be just the username, so the problem could probably be fixed by replacing the get_builduser() call with get_builduser().name (although i'm not sure that is correct lua syntax)

**Comment by juster** [comment]
eew yeah guess I missed one

**Comment by juster** [comment]
should be fixed now
