### ISSUE TITLE
Clyde tries to install package= instead of package

### ISSUE THREAD

**Issue by rmbl** [Kiwi/clyde#139]
I tried to install the package banshee-community-extensions from AUR.
One of the dependencies is banshee==2.0.1. Instead of searching for the package banshee (which is already installed in the required version), clyde tries to find and install the package banshee= from AUR which of course fails.

**Comment by juster** [comment]
That is not the right syntax for a PKGBUILD file. You aren't supposed to use == for depends. You are supposed to use only one =. Tell the package maintainer to fix it. That package probably won't even build with makepkg on its own (which you might try before blaming an AUR helper).

**Comment by rmbl** [comment]
It does build with makepkg. That's why I thought it might be a problem with clyde.

**Comment by stuartpb** [comment]
I'd call that an issue in makepkg then.
