### ISSUE TITLE
^D in prompt causes crash

### ISSUE THREAD

**Issue by hut** [Kiwi/clyde#14]
Here's a minor bug:

When pressing ctrl+D in the prompt for the packages to be installed, clyde crashes instead of cleanly exiting:

lua: /usr/share/lua/5.1/clydelib/util.lua:44: bad argument #1 to 'strfind' (string expected, got nil)

Full traceback here:
http://pastebin.com/xrthAPKZ

**Comment by Kiwi** [comment]
Thanks, I will fix this soon most likely.

**Comment by Kiwi** [comment]
It is fixed now in my local version, I just have to commit it and push. I have done a bunch of fixes today so it will come with them later tonight as that is how I do it. >.>
