### ISSUE TITLE
Would like to see -U implemented

### ISSUE THREAD

**Issue by ShoeUnited** [Kiwi/clyde#15]
I know it may be a nitpick issue, but it'd be nice to add a -U option for the full automation experience.
I know you're working on this, I just thought maybe a little comment message would help cheer you on. Thanks for all you've done so far. I can't wait to see what comes up next.  :)

-Shoe

**Comment by Kiwi** [comment]
Ok, so I could have sworn I had this in already but I guess it was only partly finished. >.> I have added and pushed it, hopefully there are not bugs (it is hard to test all scenarios) but if anyone finds any let me know! =D
