### ISSUE TITLE
clyde -Si does not work for packages when specified by repository

### ISSUE THREAD

**Issue by Jonimus** [Kiwi/clyde#16]
Clyde's output
[Jon@jonums2]$ clyde -Si testing/kernel26
error: repository '/kernel26' does not exist
Pacman's output
[Jon@Jonimus2:~]$ pacman -Si testing/kernel26
Repository     : testing
Name           : kernel26
Version        : 2.6.33.1-1
URL            : http://www.kernel.org
Licenses       : GPL2  
Groups         : base  
Provides       : None
Depends On     : coreutils  kernel26-firmware>=2.6.32  module-init-tools  
                 mkinitcpio>=0.5.20  
Optional Deps  : crda: to set the correct wireless channels of your country
Conflicts With : None
Replaces       : kernel24  kernel24-scsi  kernel26-scsi  alsa-driver  
                 ieee80211  hostap-driver26  pwc  nforce  squashfs  
                 unionfs  ivtv  zd1211  kvm-modules  iwlwifi  rt2x00-cvs  
                 gspcav1  atl2  wlan-ng26  rt2500  
Download Size  : 22588.08 K
Installed Size : 108160.00 K
Packager       : Thomas Bächler thomas@archlinux.org
Architecture   : x86_64
Build Date     : Mon 15 Mar 2010 01:14:51 PM CDT
MD5 Sum        : af33f6be2ec7ef0a8b02db82917857b0
Description    : The Linux Kernel and modules

It works fine when run without specifiing a repository..

**Comment by Kiwi** [comment]
Fixed in local afaict, and improved! Should be pushed pretty soon then I will close. ^_^
