### ISSUE TITLE
Clyde -S crashes without network

### ISSUE THREAD

**Issue by Daenyth** [Kiwi/clyde#17]
daenyth@Bragi ~ $ sudo clyde -S eclim
Password: 
:: eclim package not found, searching for group...
:: eclim group not found, searching AUR...
LOG_ERRORdaenyth@Bragi ~ $ ping google.com
ping: unknown host google.com
[net back up]
daenyth@Bragi ~ $ sudo clyde -S eclim
error: failed to init transaction(unable to lock database)
  if you're sure a package manager is not already
  running, you can remove /var/lib/pacman/db.lck

**Comment by Kiwi** [comment]
I am pretty sure this is fixed in local. It took me a while to track down just where it was failing but I did it in the end and figured out a solution! I will push it later tonight with the other patches I have been working on and close when I have.
