### ISSUE TITLE
[bug] dependencies-problems not shown if uninstall & german locals

### ISSUE THREAD

**Issue by muunleit** [Kiwi/clyde#19]
If I try to uninstall something with dependencies-problems, clyde doesn't show the packages which cause them.

[code]
sudo clyde -Rs libpng
checking dependencies...
error: failed to prepare transaction (Kann Abhängigkeiten nicht erfüllen)
[/code]

After " export LC_ALL="C" " it works fine.

[code]
sudo clyde -Rs libpng
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: cairo: requires libpng>=1.4.0
:: feh: requires libpng
...
[/code]

**Comment by Kiwi** [comment]
I believe I have fixed this in local I just have not committed or pushed it yet.

**Comment by Kiwi** [comment]
Pushed, reopen if it is still broken.

**Comment by muunleit** [comment]
I can't reopen, but there seems to be something wrong. It's the same in german and with "export LC_ALL='C'"

[code]
sudo clyde -R libpng  
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
lua: /usr/share/lua/5.1/clydelib/remove.lua:105: attempt to index global 'C' (a nil value)
stack traceback:
    /usr/share/lua/5.1/clydelib/remove.lua:105: in function 'clyde_remove'
    /usr/share/lua/5.1/clydelib/remove.lua:148: in function </usr/share/lua/5.1/clydelib/remove.lua:147>
    (tail call): ?
    /usr/bin/clyde:1018: in function </usr/bin/clyde:929>
    (tail call): ?
    [C]: ?
[/code]

And there are 2 warnings while the todays build.
[code]
==> Starting make...
Initialized empty Git repository in /tmp/clyde-muunleit/clyde-git/clyde-git/src/clyde-build/.git/
gcc -Wall -W -O2 -fPIC  -lalpm `pkg-config --cflags lua` -shared -o lualpm.so lualpm.c -pedantic -D_FILE_OFFSET_BITS=64 -std=c99 -D_GNU_SOURCE
gcc -Wall -W -O2 -fPIC  `pkg-config --cflags lua` -shared -o clydelib/utilcore.so clydelib/utilcore.c -pedantic -D_FILE_OFFSET_BITS=64 -std=c99 -D_GNU_SOURCE
gcc -Wall -W -O2 -fPIC  -shared -o clydelib/signal.so clydelib/lsignal.c
clydelib/lsignal.c: In function 'sighook':
clydelib/lsignal.c:167: warning: unused parameter 'ar'
clydelib/lsignal.c: In function 'l_signal':
clydelib/lsignal.c:231: warning: 'sig' may be used uninitialized in this function
install -Dm755 lualpm.so /tmp/clyde-muunleit/clyde-git/clyde-git/pkg/usr/lib/lua/5.1/lualpm.so
gcc -Wall -W -O2 -fPIC  -lalpm `pkg-config --cflags lua` -shared -o lualpm.so lualpm.c -pedantic -D_FILE_OFFSET_BITS=64 -std=c99 -D_GNU_SOURCE
install -Dm755 clyde /tmp/clyde-muunleit/clyde-git/clyde-git/pkg/usr/bin/clyde
install -dm755 /tmp/clyde-muunleit/clyde-git/clyde-git/pkg/usr/share/lua/5.1/clydelib
install -Dm755 clydelib/utilcore.so /tmp/clyde-muunleit/clyde-git/clyde-git/pkg/usr/lib/lua/5.1/clydelib/utilcore.so
install -Dm755 clydelib/signal.so /tmp/clyde-muunleit/clyde-git/clyde-git/pkg/usr/lib/lua/5.1/clydelib/signal.so
install -Dm644 clydelib/*.lua /tmp/clyde-muunleit/clyde-git/clyde-git/pkg/usr/share/lua/5.1/clydelib/
==> Tidying install...
...
[/code]

Removing packages with no dependencies-problems still works normal.

**Comment by Kiwi** [comment]
There have always been 2 warnings. The color thing is fixed now. Sorry about that and thanks.

**Comment by muunleit** [comment]
Ok, I didn't noticed the warnings before. 
Can you reopen this issue because of the problem in remove.lua?

**Comment by muunleit** [comment]
[Closed] It works now. :-)
