### ISSUE TITLE
Output coloring does not match default colors

### ISSUE THREAD

**Issue by SanskritFritz** [Kiwi/clyde#2]
I'm using black on white colors in the terminal. The output of clyde switches to white on black for descriptions. It looks ugly, and it is hard to read.

**Comment by Kiwi** [comment]
I was planning to implement a set of color themes for people such as yourself sometime. It was low priority but since you asked I will try to get it in sometime this/next week. There will also be a user configurable color profile so if you do not like any of what I provide you can set it yourself.

**Comment by SanskritFritz** [comment]
Wow, thanks!

**Comment by Kiwi** [comment]
Could you post what terminal/colors you are using so that I can figure out what colors should be what? I have not been able to make it as you describe.

**Comment by SanskritFritz** [comment]
[Background]
Bold=false
Color=255,255,255
Transparency=false

[BackgroundIntense]
Bold=false
Color=255,255,255
Transparency=false

[Color0]
Bold=false
Color=0,0,0
Transparency=false

[Color0Intense]
Bold=false
Color=104,104,104
Transparency=false

[Color1]
Bold=false
Color=178,24,24
Transparency=false

[Color1Intense]
Bold=false
Color=255,84,84
Transparency=false

[Color2]
Bold=false
Color=0,128,0
Transparency=false

[Color2Intense]
Bold=false
Color=0,128,0
Transparency=false

[Color3]
Bold=false
Color=178,104,24
Transparency=false

[Color3Intense]
Bold=false
Color=255,128,0
Transparency=false

[Color4]
Bold=false
Color=24,24,178
Transparency=false

[Color4Intense]
Bold=false
Color=84,84,255
Transparency=false

[Color5]
Bold=false
Color=178,24,178
Transparency=false

[Color5Intense]
Bold=false
Color=255,84,255
Transparency=false

[Color6]
Bold=false
Color=0,128,128
Transparency=false

[Color6Intense]
Bold=false
Color=84,255,255
Transparency=false

[Color7]
Bold=false
Color=178,178,178
Transparency=false

[Color7Intense]
Bold=false
Color=255,255,255
Transparency=false

[Foreground]
Bold=false
Color=0,0,0
Transparency=false

[ForegroundIntense]
Bold=true
Color=0,0,0
Transparency=false

[General]
Description=Black on White
Opacity=1

**Comment by Kiwi** [comment]
Thanks, what terminal you are using would help as well. I have done most of the work for this just need to figure out the colors for the alternate profiles mostly. >.>

**Comment by SanskritFritz** [comment]
I'm using the default KDE4 terminal, Konsole. But the color scheme I posted is a customised one, based on the normal Black on White profile.

**Comment by nuno-aj-aniceto** [comment]
If you don't mind as this may be somehow unrelated to the issue,
I would sugest the possibility of adding a flag for enabling/disabling colors.

I think it would resolve the issue and please both persons who use colors as those who use not colors.

**Comment by Kiwi** [comment]
--nocolor and --color flags have existed for weeks. I just, uh, have not added any information about Clyde's extra flags to the --help....

Protip: by default, if you redirect the output of clyde, ie. | less or > file, or whatever, it will strip colors. (This is so you do not end up with ansi escape codes in the text file case, it has no way of knowing the difference though so it has to be all or nothing) --color will override the stripping.

**Comment by nuno-aj-aniceto** [comment]
great ! 

thanks. I think you have there a brilliant replace for yaourt :D

**Comment by cabrilo** [comment]
Kiwi, how possible is it to create a default color scheme that's suitable for both dark and light background? 

E.g. when I use ls --color=auto on either white or back background, I get a readable result.

**Comment by Kiwi** [comment]
I changed the files to use bright instead of white bold, hopefully this fixes the issue. I have not got color profiles done as you may have noticed but they are still up there on my priority list, sorry I have taken so long. For now I will consider this closed due to the change but reopen if it is not fixed for you, in the meantime I will try to get the color profiles in.
