### ISSUE TITLE
[bug] clyde -R -u doesn't work

### ISSUE THREAD

**Issue by muunleit** [Kiwi/clyde#21]
The '--unneeded' option seems to miss something.

[code] 
clyde -R -u  
error: no targets specified (use -h for help)
[/code]

**Comment by Kiwi** [comment]
[kiwi@lappy:~]$ s clyde -R -u                                                           (03-30 13:30)
error: no targets specified (use -h for help)
[kiwi@lappy:~]$ s pacman -R -u                                                          (03-30 13:30)
error: no targets specified (use -h for help)
[kiwi@lappy:~]$

Unless you can show that pacman -R -u shows something when you do that I am going to say it is not a bug. It should let you reopen this if that is the case, if not just email me.

**Comment by muunleit** [comment]
Sorry, I asked Ghost in the irc before I posted here and he confirms this a bug, but it seems I / we misunderstood this option.
