### ISSUE TITLE
Slight delay after Proceed with Installation.

### ISSUE THREAD

**Issue by ShoeUnited** [Kiwi/clyde#26]
There's a slight hang between "Proceed with installation? [Y/n]"  and ==> Downloading foobar.tar.gz   when doing -Syu --aur   About 10 seconds.  Then prompt for editing PKGBUILD.  The rest pop up rather instantaneously. 

Kiwi has told me that it is doing some work behind the scenes during that delay.  It is to be expected.

**Comment by nogweii** [comment]
Is this still applicable?

**Comment by Kiwi** [comment]
Yes, evaryont.

**Comment by juster** [comment]
This shouldn't be a problem anymore. There is still a delay but it is after the downloading message...
