### ISSUE TITLE
"clyde -Qc" gives error if no changelog found

### ISSUE THREAD

**Issue by skualito** [Kiwi/clyde#3]
clyde -Qc pacman
lua: /usr/share/lua/5.1/clydelib/packages.lua:203: attempt to call global 'g' (a nil value)
stack traceback:
    /usr/share/lua/5.1/clydelib/packages.lua:203: in function 'dump_pkg_changelog'
    /usr/share/lua/5.1/clydelib/query.lua:325: in function 'display'
    /usr/share/lua/5.1/clydelib/query.lua:414: in function 'clyde_query'
    /usr/share/lua/5.1/clydelib/query.lua:436: in function 'main'
    /usr/bin/clyde:974: in function '?'
    /usr/bin/clyde:981: in function </usr/bin/clyde:899>
    (tail call): ?
    [C]: ?

From pacman 
pacman -Qc pacman
Erreur: changelog non disponible pour 'pacman'.

**Comment by Kiwi** [comment]
Thanks for pointing that out, this has been fixed.
