### ISSUE TITLE
[bug] Second progress line for AUR

### ISSUE THREAD

**Issue by muunleit** [Kiwi/clyde#32]
I get a second progress line when clyde has checked AUR for updates.

```
 aur                     29/ 29 [----------------------------] 100%
[----------------------------] 100%
```

**Comment by Kiwi** [comment]
I know about this, it only happens occasionally and only for some people, I am not sure how to fix it but I think I can if I rearrange some stuff..., thanks.

**Comment by Kiwi** [comment]
I believe this is fixed.

**Comment by muunleit** [comment]
yes, works
