### ISSUE TITLE
/etc/clyde.conf permissions are left up to the umask setting

### ISSUE THREAD

**Issue by IsaacG** [Kiwi/clyde#33]
clyde creates a /etc/clyde.conf when it does not exist and you run clyde as root.

Files in /etc/ should, in general, be creates by the package manager and with permissions 644. clyde leaves the permissions up to the umask env setting. Which will often lead to 644. But not always. After making /etc/clyde.conf, it should chmod it to 644

**Comment by Kiwi** [comment]
This is fixed.
