### ISSUE TITLE
Clyde doesn't like ^C while installing packages.

### ISSUE THREAD

**Issue by Daenyth** [Kiwi/clyde#36]
(6/6) checking for file conflicts                  [#########################################] 100%
(1/6) upgrading glib2                              [#########################################] 100%
(2/6) upgrading atk                                [#########################################] 100%
(3/6) upgrading pango                              [#########################################] 100%
^C
Interrupt signal received

^C/6) upgrading gtk2                               [######-----------------------------------]  17%
Interrupt signal received

^C/6) upgrading gtk2                               [########---------------------------------]  21%
Interrupt signal received

^C/6) upgrading gtk2                               [###########------------------------------]  28%
Interrupt signal received

^C/6) upgrading gtk2                               [############-----------------------------]  31%
Interrupt signal received

^C/6) upgrading gtk2                               [##############---------------------------]  35%
Interrupt signal received

^C/6) upgrading gtk2                               [################-------------------------]  40%
Interrupt signal received

^C/6) upgrading gtk2                               [##################-----------------------]  44%
Interrupt signal received

^C/6) upgrading gtk2                               [###################----------------------]  47%
Interrupt signal received

^C/6) upgrading gtk2                               [####################---------------------]  49%
Interrupt signal received

^C/6) upgrading gtk2                               [####################---------------------]  51%
Interrupt signal received

^C/6) upgrading gtk2                               [#######################------------------]  57%
Interrupt signal received

(4/6) upgrading gtk2                               [#########################################] 100%
^C
Interrupt signal received

^C
Interrupt signal received

error: failed to release transaction (transaction not initialized)

**Comment by Kiwi** [comment]
Not a bug, but it is a dupe, see here:

http://github.com/Kiwi/clyde/issues/closed#issue/34
