### ISSUE TITLE
[Feature-Request] show opt-deps

### ISSUE THREAD

**Issue by muunleit** [Kiwi/clyde#37]
Pacman shows the optional dependencies after installing a package.
Could you add this to clyde, too?

**Comment by Kiwi** [comment]
It should already...can you show me an example that does with pacman but not clyde?

**Comment by muunleit** [comment]
Pacman
    .....
    checking package integrity...
    (1/1) checking for file conflicts                   [-------] 100%
    (1/1) installing xarchiver                          [------] 100%
    Optional dependencies for xarchiver
        tar: TAR support
        gzip: GZIP support
        bzip2: BZIP2 support
        zip: ZIP support
        unzip: ZIP support
        unrar: RAR support
        p7zip: 7z support
        arj: ARJ support
        lha: LHA support
        lzma-utils: LZMA support
        lzop: LZOP support

Clyde
     ......
     checking package integrity...
     (1/1) checking for file conflicts                  [------] 100%
     (1/1) installing xarchiver                         [-------] 100%

**Comment by Kiwi** [comment]
Ok so apparently I had a TODO for the required functions and forgot about it, this should be fixed now. Thanks.

**Comment by muunleit** [comment]
It works, but in every case.
     ....
     (11/22) installing pm-quirks                       [---] 100%
     Optional dependencies for pm-quirks
         None
     .....
     (19/22) installing hdf5                            [---] 100%
     Optional dependencies for hdf5
         None

**Comment by Kiwi** [comment]
Update Clyde. I fixed that about 20 hours ago.

**Comment by muunleit** [comment]
sorry
