### ISSUE TITLE
Bold doesn't go away after grepped output.

### ISSUE THREAD

**Issue by FrozenFox** [Kiwi/clyde#38]
If I run clyde -Q, everything works as expected and causes no trouble. If I clyde -Q | grep SomeExistingLocalPackage however, the terminal is emboldened from then on until I run clyde -Q or something that otherwise returns it to normal output. The same thing with pacman-color does not have this issue (for that matter, it returns non-colored text, which I don't quite understand since -Q alone returns output similar to clyde's).

**Comment by Kiwi** [comment]
What terminal? When did you last upgrade? Output of -Q clyde-git please. (It works perfectly here.)

**Comment by FrozenFox** [comment]
Ffs, I swear I typed that it was gnome-terminal before.. ><

Anyway, I updated clyde just before posting to be sure, and everything else is updated sometime between daily and weekly. I -Syu'ed before that as well, also to be sure.

$ clyde -Q clyde-git
local/clyde-git 20100420-1

**Comment by FrozenFox** [comment]
Ftr I just noticed that it appears to change the color of green I have set in my PS1 as well to a more lime green like the -Q output, if that's helpful at all.

In .bashrc:

GREEN=`tput setf 2`
PS1='[$GREEN]\u@\h [$BLUE]\w/[$GREEN] \$[$WHITE] '

After the weird character overflow, the pine-ish green name@host is bold lime-ish green.

Edit: annd.. github seems to be making a box out of the bashrc stuff enclosed with ` .

Edit2: On further note, I tried to see if my specific query or packages caused it for some reason, and that's not the case. Anything does it that I try.

**Comment by Kiwi** [comment]
Hmm, that is weird. I will look into it.

**Comment by Kiwi** [comment]
This has been fixed.

**Comment by FrozenFox** [comment]
Sweet. It works indeed. Thanks ^^
