### ISSUE TITLE
Few bugs and feature requests

### ISSUE THREAD

**Issue by nuno-aj-aniceto** [Kiwi/clyde#4]
The bugs:
- just to notice that clyde -Scc is not working yet.
- clyde -Syu --aur does not update the AUR packages
- clyde -Syu sometimes do not upgrade the stuff, doing it again will just download the packages, not install them.
- clyde -Syu will print lines and lines of output (too many lines, check this: http://img38.imageshack.us/img38/5092/clydeupgrade.png )
- clyde do not respond immediatly to the Ctrl+C command (Cancel/Abort signal - SIGTERM) although the Ctrl+Z signal works fine.

The feature requests:
- the use of the 'aurvote' tool
- the yaourt -G flag (to download the source package from ABS/AUR - PKGBUILD and the source stuff)
- the -Sb flag (to build from source: ABS or AUR)

Thanks for this big effort for bringing clyde. thanks!!

**Comment by vodik** [comment]
Adding "clyde -G <package>" to just grab the PKGBUILD would be a lovely addition too.

**Comment by nogweii** [comment]
Why not modify the -Sw behaviour, when downloading an AUR package? -Sw already means "download" in pacman-ish :P

**Comment by tcourbon** [comment]
It look like clyde ignore the pacman's IgnorePkg directive. Is there something special with this one I missed or just a pending implementation ?

**Comment by Kiwi** [comment]
It should work. Are you sure you modified clyde.conf and not pacman.conf? If a clyde.conf exists it uses that.

**Comment by Kiwi** [comment]
Closing this due to all the bugs being fixed (or not bugs, like ctrl+c) and all but the aurvote (which is unlikely to go in, if you feel it should repost with just that) features implemented.
