### ISSUE TITLE
[Feature-Request] Save AUR packages to cache

### ISSUE THREAD

**Issue by dcampbell24** [Kiwi/clyde#41]
Typically, when using -U to install a package, it will be saved somewhere on one's computer. But, when installing from AUR, the packages are in /tmp and get lost. It would be nice to instead have them saved to /var/pacman/cache/, or, at least, have an option to do this.

**Comment by nogweii** [comment]
what about setting `PKGDEST` in /etc/makepkg.conf?

**Comment by dcampbell24** [comment]
Cool, I didn't know about that feature. Thanks.
