### ISSUE TITLE
linux/limits.h

### ISSUE THREAD

**Issue by chris-kun** [Kiwi/clyde#42]
Initialized empty Git repository in /home/stythyss/clyde-git/src/clyde-build/.git/
gcc -Wall -W -O2 -fPIC  -lalpm `pkg-config --cflags lua` -shared -o lualpm.so lualpm.c -pedantic -D_FILE_OFFSET_BITS=64 -std=c99 -D_GNU_SOURCE
In file included from /usr/include/bits/posix1_lim.h:157,
                 from /usr/include/limits.h:145,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/4.4.3/include-fixed/limits.h:122,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/4.4.3/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-unknown-linux-gnu/4.4.3/include-fixed/limits.h:11,
                 from lualpm.c:8:
/usr/include/bits/local_lim.h:39:26: error: linux/limits.h: No such file or directory
make: **\* [lualpm] Error 1
==> ERROR: Build Failed.

any ideas?

**Comment by thomasdziedzic** [comment]
pkgfile -v limits.h | grep linux
core/linux-api-headers (2.6.33.2-1) : /usr/include/linux/limits.h

please install the package and retry again

**Comment by nogweii** [comment]
Should linux-api-headers be included as a makedepend? Kinda kidding, kinda serious.

Hosed my system, as an upgrade failed in the middle - some packages had already been removed/upgraded while others had not yet, so among other packages, linux-api-headers isn't installed, and pacman is broken (missing a file in /usr/lib) and clyde is as well.

**Comment by thomasdziedzic** [comment]
wait, what? linux-api-headers gets installed as part of base, and it was created a long time ago to replace kernel26-headers, iirc. If you updated regularly you wouldn't have this issue. Also, how did you get from a build failure, to upgrading your system? If clyde breaks during an upgrade, then you should file a separate bug report and close this one.

**Comment by nogweii** [comment]
Yeah. This doesn't directly affect me. Regardless, it was my own doing, not clyde's, that broke the system. I was able to fix it.

Presumably, Stythys has been able to fix it, and this is an old enough ticket, that this is now closed. If this is still happening, open another ticket (though it shouldn't)
