### ISSUE TITLE
support "su" as alternative to sudo

### ISSUE THREAD

**Issue by ammad** [Kiwi/clyde#45]
Title says is all.. Meanwhile have to use root

**Comment by Mais** [comment]
This is the one feature keeping me from using Clyde.

**Comment by Kiwi** [comment]
This is planned.

Until then...if you set SUDO_USER via export manually you can run it with su without issues.

export SUDO_USER="youruser"

**Comment by Kiwi** [comment]
Hurr, I suck at closing my own issues. I added this sometime around May 22nd. Use BuildUser in clyde.conf or --user flag.

Some specifics here if you're interested http://bbs.archlinux.org/viewtopic.php?pid=763000#p763000
