### ISSUE TITLE
Lua spawning nano (may be user issue)

### ISSUE THREAD

**Issue by ShoeUnited** [Kiwi/clyde#47]
Two days ago, I was running clyde to check a pkgbuild of the below example for my sister.    When I went through the install process I hit ^C to kill it (as I did not need it for myself).  Little did I know, lua was still spawning nano to edit the pkg build, in two days time nano was taking 92-99% of the cpu.  Not sure if it's a bug exactly, I know it's partially user error (better to install then uninstall right away).

top:
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND  
 9361 root      20   0  8520 1612 1096 R   98  0.0   0:02.12 nano       

pstree -a:
  ├─lua /usr/bin/clyde -S flvtomp3
  │   └─nano PKGBUILD

Killing lua, then killing nano solved the immediate issue.

**Comment by nogweii** [comment]
Still happening?

**Comment by ShoeUnited** [comment]
Yes, I can testify that something along those lines keeps happening.  Whether you do ctrl+c ctrl+z or if clyde just crashes, and it usually only takes an hour on my machine.  I've eliminated everything else but lua and clyde.
