### ISSUE TITLE
Coloring oddness with tmux/screen

### ISSUE THREAD

**Issue by squarehimself** [Kiwi/clyde#49]
Not sure what's going on here, but I get some strange coloring output with both tmux and screen where clyde puts a colored background to the info text. Without tmux/screen colored output is fine. Happens with any terminal the session is connected to.

Screenshot:
http://imgur.com/HZRvk.png

**Comment by Kiwi** [comment]
Clyde uses 'italic' for that text, and screen and tmux do not handle it right. Not a bug in Clyde, though I might be able to alter behavior... It will be remedied when I finally get color profiles like I have been meaning to for months...
