### ISSUE TITLE
-S should not require root directly

### ISSUE THREAD

**Issue by reactormonk** [Kiwi/clyde#51]
... instead it should ask for pw if needed, so you can build AUR packages as user.

**Comment by Kiwi** [comment]
It drops to the user as given by the SUDO_USER environment variable when it runs makepkg. It will be changed eventually to let you run it without sudo (though I believe you can already if you export SUDO_USER somewhere...) and drop to a specified user with su -c or as root user. I think there are already open issues on that though.

Changing to have a prompt will not happen as Clyde is not a wrapper. Check the arch bbs and other issues for info on that.
