### ISSUE TITLE
pacman 3.4.0 compitability

### ISSUE THREAD

**Issue by Huulivoide** [Kiwi/clyde#58]
Buildign clyde whir pacman 3.4.0 will fail, mostlikely due to some changes in libalpm.

**Comment by juster** [comment]
Until my changes are merged into the main repo you can use my fork at http://github.com/juster/clyde.  Either hack the existing clyde _PKGBUILD_ or use the one at my repo.  You can use the following commands on your shell to download my PKGBUILD and build the _clyde-fork-git_ package:

```
wget http://xrl.us/clydepkg
makepkg
```
