### ISSUE TITLE
Clyde keeps asking to edit PKGBUILD until I say 'no'

### ISSUE THREAD

**Issue by hoelzro** [Kiwi/clyde#62]
When Clyde asks me if I want to edit PKGBUILD (or another file), it keeps asking until I say 'no', even after I've edited the file.

**Comment by nogweii** [comment]
This is on purpose, and probably won't be fixed.

We've had a discussion about this, and while it sounds nice, what if you make a mistake in the PKGBUILD? When could you edit it then?

This behaviour is not going to change any time soon. (And it's already been decided, I just can't find the right bug report)

EDIT: Ah! It's #13 - see Kiwi's message.

**Comment by nogweii** [comment]
Since this is a duplicate, I'm closing this one.
