### ISSUE TITLE
Clyde doesn't respect IgnorePkg in clyde.conf for AUR packages

### ISSUE THREAD

**Issue by d-miketa** [Kiwi/clyde#65]
I uncommented IgnorePkg and added foo2zjs after the equivalency symbol in /etc/clyde.conf. Still, when I update my system (including the packages from AUR), Clyde offers me an update of this package. Foo2zjs is poorly maintained and often cannot be compiled because of wrong md5sums (changing them is a hassle, the package works on my system in its current version), so I would prefer not to update it at all.

**Comment by codedmart** [comment]
I can confirm this is happening from AUR packages. I added a package from AUR to the IgnorePKG list and clyde ignores it.

**Comment by juster** [comment]
Fixed as of 0.03.13. Thanks to RamsesDeNorre's patch.
