### ISSUE TITLE
Clyde doesn't show file conflicts when building from AUR or using clyde -U

### ISSUE THREAD

**Issue by OttoAllmendinger** [Kiwi/clyde#69]
<pre>
# sudo touch /usr/bin/keepnote
# sudo clyde -S keepnote

[...]

(1/1) checking for file conflicts                  [######################################] 100%
error: failed to commit transaction (conflicting files)
</pre>

Without displaying the paths of the conflicting files

**Comment by OttoAllmendinger** [comment]
patch: 8473e79093c9ba7db93a190205b0183c82edea86

**Comment by juster** [comment]
Fixed in 0.03.02.
