### ISSUE TITLE
Clyde hangs before finishing AUR build.

### ISSUE THREAD

**Issue by ShoeUnited** [Kiwi/clyde#7]
I use nano as an editor.  Otherwise clyde was built from AUR.  
When viewing the PKGBUILD, it seems that an odd number of views causes it to hang when it checks for dependencies.  I ran this last test and let it sit while I slept (roughly 8 hours) just to make sure I wasn't being hasty with ^C.  Also, re-running the command it will finish without errors.

http://pastebin.ca/1835683

I have put the issue into a pastebin so you can see a reproduction of the error, and to conserve on space bloat.  I did it on something I don't need so it's no big deal.

Clyde is superfast and I love it.  If there's a --debug style option, I'd be happy to run it and provide the errors it spits out. :)

-Shoe

**Comment by ShoeUnited** [comment]
As per your request, I'm providing more examples. :)

xkcdviewer (AUR) http://pastebin.ca/1836687

vlcskineditor (AUR) --Finished without problems-- http://pastebin.ca/1836701

bin32-zsnes (AUR) --Finished without problems-- http://pastebin.ca/1836706

aqualung-svn (AUR) http://pastebin.ca/1836736

aurvote (AUR)  (removed wget and aurvote then reinstalled aurvote) http://pastebin.ca/1836740

**Comment by Kiwi** [comment]
This seems to be fixed, let me know if you find anything broken with the fix >.> if not I will close this.

**Comment by ShoeUnited** [comment]
I just tried it with the -Rc wget   then -S aurvote and it works perfectly now. :)  Thank you so much. :D
