### ISSUE TITLE
SIGINT

### ISSUE THREAD

**Issue by grai** [Kiwi/clyde#71]
When I press ^C at a prompt, I expect clyde to exit immediately.  It doesn't.  I have to press Enter too.

Apart from this minor annoyance, clyde's great.  :-)

```
==> Proceed with installation? [Y/n] ^C
```

**Comment by OttoAllmendinger** [comment]
I am working on it (239889f92740699db0e59cd6d116f912e0331d27). I hope I can get it done by the end of next week

**Comment by juster** [comment]
Fixed in v0.03.03. Thanks Otto.
