### ISSUE TITLE
Clyde doesn't show user if package is newer than installed version

### ISSUE THREAD

**Issue by Evanlec** [Kiwi/clyde#72]
When results of packages are shown, it properly shows [installed] next to packages that are installed locally, but it fails to signify if the package is newer and could be upgraded.

For ex. I have aur/virtualbox_bin 3.2.6-1 installed on my system, clyde shows aur/virtualbox_bin 3.2.8-1 as [installed], making the user think that 3.2.8 is installed locally when in fact it is not.

Yaourt I think used to point out newer versions so it would be nice if Clyde would as well.

**Comment by juster** [comment]
Locally installed versions are now shown properly in search results.
