### ISSUE TITLE
XferCommand not used

### ISSUE THREAD

**Issue by Dieterbe** [Kiwi/clyde#74]
in /etc/clyde.conf, i have:
XferCommand = /usr/bin/wget  --limit-rate=20k --passive-ftp -c -O %o %u

however, when I do `clyde -Syu`, i see no wget process. not during the database synchronisation, and not during the package downloading either.

**Comment by juster** [comment]
XferCommand isn't implemented but it should be soon. rck has sent a pull request which implements it but I would like to modify it slightly first. I would like to make the lualpm interface more generic and lua-ish.

**Comment by juster** [comment]
This is implemented as of version v0.03.06.
