### ISSUE TITLE
No man page, not even 'see pacman(8)'

### ISSUE THREAD

**Issue by nogweii** [Kiwi/clyde#8]
Clyde definetly needs a man page. It could be very simple: Clyde is written in Lua. It supports the AUR. See pacman(8) for more information.

If learning the roff syntax is too much, I recommend `ronn` though that's ruby/markdown based. Perhaps some other utility?

**Comment by ShoeUnited** [comment]
I too was looking for a manpage of sorts.  Good idea. :)

**Comment by Kiwi** [comment]
Patches welcome. :)

I will probably get to this eventually but as of now it is not high priority since the options are mostly the same as pacman, and -h explains the extra ones.

**Comment by Kiwi** [comment]
davekong has created a man page so I am closing this. Thanks davekong!

**Comment by nogweii** [comment]
Hate to get nit picky, but a cursory overview of the Makefile doesn't seem to mention the man page at all...

**Comment by Kiwi** [comment]
I do not know what you are talking about, it is right here... ;D

```
$(INSTALL_DATA) man/clyde.8 $(DESTDIR)$(man8dir)/clyde$(manext)
```
