### ISSUE TITLE
--aur and --ignore do not work together

### ISSUE THREAD

**Issue by smyrman** [Kiwi/clyde#80]
When you upgrade packages with the --aur switch

$ sudo clyde -Syu --aur

Packages from AUR that is specefied in IgnorePkg, NoUpgrade, HoldPkg or with the --ignore option (or all of those), is still listed for installation:

$ sudo clyde -Su --aur --ignore xbmc-svn
:: Starting full system upgrade...
:: Synchronizing AUR database...
 aur                    101/101 [####################################################] 100%

==> Installing the following packages from AUR  
Targets (4): libpng12  playonlinux  pngcrush  xbmc-svn 

==> Proceed with installation? [Y/n]

**Comment by smyrman** [comment]
Ops.. I see that this issue is a duplicate of #65  - sorry

**Comment by juster** [comment]
Fixed in 0.03.13. Thanks for reporting even if its a duplicate.
