### ISSUE TITLE
Don't hardcode build directory

### ISSUE THREAD

**Issue by Tenzer** [Kiwi/clyde#82]
Currently the directory where builds are made is hardcoded to /tmp/clyde-[username]/. It would be a nice thing to be able to change what directory should be used for that, since people may not have enough space in that location to ie. build the "kernel26-pae" AUR package, or people may have an SSD drive in the machine which is mounted elsewhere.

**Comment by juster** [comment]
The --builddir option and BuildDir configure file entry has been added. I hope this fixes your problem.

**Comment by Tenzer** [comment]
That's great, thanks!
