### ISSUE TITLE
lua: /usr/bin/clyde:672: attempt to call field 'getbuilduser' (a nil value)

### ISSUE THREAD

**Issue by thechitowncubs** [Kiwi/clyde#96]
[mike@myhost yaourt]$ sudo clyde -S awesome
You do not yet have a clyde.conf, would you like to create one? [Y/n] y
Please enter your default text editor: vim
You entered 'vim' as your default editor, is this correct?  [Y/n] y
lua: /usr/bin/clyde:672: attempt to call field 'getbuilduser' (a nil value)
stack traceback:
        /usr/bin/clyde:672: in function 'config_init'
        /usr/bin/clyde:983: in function 'main'
        /usr/bin/clyde:1112: in main chunk
        [C]: ?

**Comment by juster** [comment]
Thanks for reporting this. Fixed as of 0.03.11.

**Comment by thechitowncubs** [comment]
You rock, thanks for being awesome.
